export const styles = {
  pageWrapper: {
    fontFamily: "Arial, sans-serif",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    minHeight: "100vh",
    padding: "20px",
    color: "#333",
  },
  title: {
    textAlign: "center",
    color: "#fff",
    marginBottom: "5px",
    fontSize: "2.5rem",
    textShadow: "2px 2px 4px rgba(0,0,0,0.3)",
    fontWeight: "600",
  },
  subtitle: {
    textAlign: "center",
    color: "#fff",
    marginBottom: "40px",
    fontSize: "1.1rem",
    opacity: 0.95,
    fontWeight: "400",
  },
  roadmapContainer: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "0 20px",
  },
  roadmapTitle: {
    textAlign: "center",
    color: "#fff",
    fontSize: "1.8rem",
    marginBottom: "70px",
    fontWeight: "500",
    letterSpacing: "0.5px",
  },
  roadmapTrack: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "40px",
    padding: "20px",
  },
  roadmapItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "20px",
  },
  roadmapButton: {
    width: "180px",
    height: "180px",
    borderRadius: "50%",
    border: "4px solid rgba(255,255,255,0.3)",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    color: "white",
    fontWeight: "700",
    fontSize: "15px",
    transition: "all 0.3s ease",
    boxShadow: "0 8px 20px rgba(0,0,0,0.2)",
    textAlign: "center",
    padding: "20px",
  },
  roadmapIcon: {
    fontSize: "48px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  roadmapButtonText: {
    fontSize: "15px",
    fontWeight: "700",
    lineHeight: "1.2",
  },
  roadmapDescription: {
    textAlign: "center",
    color: "#fff",
    fontSize: "13px",
    maxWidth: "200px",
    opacity: 0.95,
    fontWeight: "400",
    lineHeight: "1.4",
  },
  progressContainer: {
    maxWidth: "1000px",
    margin: "0 auto 40px",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: "15px",
    padding: "20px",
    backdropFilter: "blur(10px)",
  },
  progressBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    position: "relative",
  },
  progressStep: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flex: 1,
    position: "relative",
  },
  progressCircle: {
    width: "50px",
    height: "50px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: "18px",
    marginBottom: "10px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.2)",
    transition: "all 0.3s ease",
  },
  progressLabel: {
    color: "#fff",
    fontSize: "12px",
    textAlign: "center",
    fontWeight: "500",
  },
  categorySelection: {
    maxWidth: "1000px",
    margin: "0 auto 40px",
    textAlign: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: "15px",
    padding: "30px",
    backdropFilter: "blur(10px)",
  },
  categoryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "20px",
    marginTop: "20px",
  },
  categoryButton: {
    padding: "25px",
    border: "none",
    borderRadius: "15px",
    cursor: "pointer",
    fontSize: "18px",
    fontWeight: "600",
    color: "white",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "10px",
    transition: "all 0.3s ease",
    boxShadow: "0 8px 16px rgba(0,0,0,0.2)",
    transform: "translateY(0)",
  },
  categoryIcon: {
    fontSize: "40px",
  },
  categoryText: {
    textAlign: "center",
  },
  questionCard: {
    maxWidth: "900px",
    margin: "0 auto 30px",
    padding: "30px",
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: "15px",
    boxShadow: "0 8px 32px rgba(0,0,0,0.1)",
    textAlign: "center",
    border: "2px solid #ddd",
  },
  questionText: {
    fontSize: "18px",
    lineHeight: "1.6",
    margin: "20px 0",
    color: "#333",
    fontWeight: "400",
  },
  changeCategoryButton: {
    padding: "10px 20px",
    backgroundColor: "#6c757d",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "16px",
    marginTop: "15px",
    fontWeight: "500",
  },
  containerStyle: {
    maxWidth: "1000px",
    margin: "0 auto 30px",
    border: "1px solid #ddd",
    padding: "20px",
    borderRadius: "15px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "20px",
    backgroundColor: "rgba(255,255,255,0.95)",
    boxShadow: "0 8px 32px rgba(0,0,0,0.1)",
  },
  webcamStyle: {
    width: "100%",
    maxWidth: "500px",
    borderRadius: "10px",
    border: "3px solid #ddd",
  },
  errorBox: {
    padding: "15px",
    backgroundColor: "#ffe0e0",
    border: "1px solid #ff6b6b",
    borderRadius: "10px",
    color: "#c92a2a",
    fontSize: "16px",
    width: "100%",
    textAlign: "center",
  },
  buttonGroup: {
    display: "flex",
    gap: "15px",
    justifyContent: "center",
    width: "100%",
  },
  button: {
    padding: "15px 30px",
    background: "linear-gradient(45deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    border: "none",
    borderRadius: "25px",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "600",
    transition: "all 0.3s ease",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  loading: {
    marginTop: "15px",
    color: "#666",
    fontSize: "16px",
    fontStyle: "italic",
    textAlign: "center",
  },
};
